package twitter

import org.joda.time.DateTime


case class User(
    contributorsEnabled: Boolean,
    createdAt: DateTime,
    defaultProfile: Boolean,
    defaultProfileImage: Boolean,
    description: Option[String],
    entities: Entities,
    favouritesCount: Int,
    followeRequestSent: Option[Boolean],
    followersCount: Int,
    friendsCount: Int,
    geoEnabled: Boolean,
    id: Long,
    idStr: String,
    isTranslator: Boolean,
    lang: String,
    listedCount: Int,
    location:Option[String],
    name: String,
    profileBackgroundColor: String,
    profileBackgroundImageUrl: String,
    profileBackgroundImageUrlHttps: String,
    profileBackgroundTile: Boolean,
    profileBannerUrl: String,
    profileImageUrl: String,
    profileImageUrlHttps: String,
    profileLinkColor: String,
    profileSidebarFillColor: String,
    profileTextColor: String,
    profileUseBackgroundImage: Boolean,
    `protected`: Boolean,
    screenName: String,
    showAllInlineMedia: Boolean,
    status: Option[Status],
    statusCount: Int,
    timeZone: Option[String],
    url: Option[String],
    utcOffset: Option[Int],
    verified: Boolean,
    withHeldInCountries: Option[String],
    withHeldScope: Option[String])
